language: ruby
rvm:
- 2.3.3
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: SpHJm4g8USEDiqYfVVmlTg7d8Xw25kRXafCi4TaNw0GvxUKfol4rdAV/byXMGU52WmrbK3nQRxoAYXv+JAxI0y6ObS17vp3Gnn8gBbsTqz9w1GU1s35H974gISIj32GpYmjmctJpbRI/XB2JNxMPuExCZIocH6WYXeoPMxGYyT0=
  app: matrix-ry
  on:
    repo: oplindstr/matrix
