EventParameterType.create(name: 'Teksti')
EventParameterType.create(name: 'Valintaruutu')
EventParameterType.create(name: 'Valintanappi')
PositionType.create(name: 'Tuutorivastaava')
Setting.create(setting: 'INDEX_NEWS_COUNT', value: '5')
Setting.create(setting: 'INDEX_EVENT_COUNT', value: '5')