EventParameterType.create(name: 'Teksti')
EventParameterType.create(name: 'Valintaruutu')
EventParameterType.create(name: 'Valintanappi')
PositionType.create(name: 'Tuutorivastaava')
Setting.create(setting: 'INDEX_NEWS_COUNT', value: '5')
Setting.create(setting: 'INDEX_EVENT_COUNT', value: '5')
Position.create(name: 'Puheenjohtaja', show_in_contact_info: true, priority: 1, admin: true)
Position.create(name: 'Varapuheenjohtaja', show_in_contact_info: true, priority: 2, admin: true)
Position.create(name: 'Taloudenhoitaja', show_in_contact_info: true, priority: 3, admin: true)
Text.create(name: 'Sanastoa', value: '')
Text.create(name: 'Etusivun info', value: '')
Text.create(name: 'Muut yhteystiedot', value: '')
Text.create(name: 'Fuksille', value: '')
Text.create(name: 'Fuksiopas', value: '')
Text.create(name: 'In English', value: '')
Text.create(name: 'Järjestö', value: '')
Text.create(name: 'Hallitus ja virkailijat', value: '')
Text.create(name: 'Virkailijaksi', value: '')
Text.create(name: 'Komero', value: '')
Text.create(name: 'Postiosoite ja toimisto', value: '')
Text.create(name: 'Sähköpostilistat', value: '')
Text.create(name: 'Yrityksille', value: '')
Text.create(name: 'Toiminta', value: '')
Text.create(name: 'Kerhot', value: '')
Text.create(name: 'Klusteri', value: '')
Text.create(name: 'Tuutorit', value: '')
Text.create(name: 'Kurssikuvauksia', value: '')
Text.create(name: 'In English', value: '')
Text.create(name: 'Tervetuloa', value: '')