EventParameterType.create(name: 'Teksti')
EventParameterType.create(name: 'Valintaruutu')
EventParameterType.create(name: 'Valintanappi')
PositionType.create(name: 'Tuutorivastaava')
Setting.create(setting: 'INDEX_NEWS_COUNT', value: '5')
Setting.create(setting: 'INDEX_EVENT_COUNT', value: '5')
Position.create(name: 'Puheenjohtaja', show_in_contact_info: true, priority: 1, admin: true)
Position.create(name: 'Taloudenhoitaja', show_in_contact_info: true, priority: 3, admin: true)